
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Poliza", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://pee.topsoluciones.com.mx/wssap/poliza.asmx?WSDL")
public class Poliza
    extends Service
{

    private final static URL POLIZA_WSDL_LOCATION;
    private final static WebServiceException POLIZA_EXCEPTION;
    private final static QName POLIZA_QNAME = new QName("http://tempuri.org/", "Poliza");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pee.topsoluciones.com.mx/wssap/poliza.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POLIZA_WSDL_LOCATION = url;
        POLIZA_EXCEPTION = e;
    }

    public Poliza() {
        super(__getWsdlLocation(), POLIZA_QNAME);
    }

    public Poliza(WebServiceFeature... features) {
        super(__getWsdlLocation(), POLIZA_QNAME, features);
    }

    public Poliza(URL wsdlLocation) {
        super(wsdlLocation, POLIZA_QNAME);
    }

    public Poliza(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POLIZA_QNAME, features);
    }

    public Poliza(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Poliza(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PolizaSoap
     */
    @WebEndpoint(name = "PolizaSoap")
    public PolizaSoap getPolizaSoap() {
        return super.getPort(new QName("http://tempuri.org/", "PolizaSoap"), PolizaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolizaSoap
     */
    @WebEndpoint(name = "PolizaSoap")
    public PolizaSoap getPolizaSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PolizaSoap"), PolizaSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POLIZA_EXCEPTION!= null) {
            throw POLIZA_EXCEPTION;
        }
        return POLIZA_WSDL_LOCATION;
    }

}
