
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PolizaSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PolizaSoap {


    /**
     * 
     * @param strXMLEntrada
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SolicitaPoliza", action = "http://tempuri.org/SolicitaPoliza")
    @WebResult(name = "SolicitaPolizaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SolicitaPoliza", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SolicitaPoliza")
    @ResponseWrapper(localName = "SolicitaPolizaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SolicitaPolizaResponse")
    public String solicitaPoliza(
        @WebParam(name = "strXMLEntrada", targetNamespace = "http://tempuri.org/")
        String strXMLEntrada);

    /**
     * 
     * @param strXMLEntrada
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SolicitaPolizaCaintra", action = "http://tempuri.org/SolicitaPolizaCaintra")
    @WebResult(name = "SolicitaPolizaCaintraResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SolicitaPolizaCaintra", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SolicitaPolizaCaintra")
    @ResponseWrapper(localName = "SolicitaPolizaCaintraResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SolicitaPolizaCaintraResponse")
    public String solicitaPolizaCaintra(
        @WebParam(name = "strXMLEntrada", targetNamespace = "http://tempuri.org/")
        String strXMLEntrada);

    /**
     * 
     * @param strXMLEntrada
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SolicitaPolizaWS", action = "http://tempuri.org/SolicitaPolizaWS")
    @WebResult(name = "SolicitaPolizaWSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SolicitaPolizaWS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SolicitaPolizaWS")
    @ResponseWrapper(localName = "SolicitaPolizaWSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SolicitaPolizaWSResponse")
    public String solicitaPolizaWS(
        @WebParam(name = "strXMLEntrada", targetNamespace = "http://tempuri.org/")
        String strXMLEntrada);

    /**
     * 
     * @param strXMLEntrada
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BajaPoliza", action = "http://tempuri.org/BajaPoliza")
    @WebResult(name = "BajaPolizaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BajaPoliza", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BajaPoliza")
    @ResponseWrapper(localName = "BajaPolizaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BajaPolizaResponse")
    public String bajaPoliza(
        @WebParam(name = "strXMLEntrada", targetNamespace = "http://tempuri.org/")
        String strXMLEntrada);

    /**
     * 
     * @param strXMLEntrada
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActualizaPoliza", action = "http://tempuri.org/ActualizaPoliza")
    @WebResult(name = "ActualizaPolizaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizaPoliza", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActualizaPoliza")
    @ResponseWrapper(localName = "ActualizaPolizaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActualizaPolizaResponse")
    public String actualizaPoliza(
        @WebParam(name = "strXMLEntrada", targetNamespace = "http://tempuri.org/")
        String strXMLEntrada);

}
